// base de datos

let precioPaquetes = [
    {
      id: 1, 
      img: "./img/paquetes/roma.jpg",
      destino: "Italia",
      nombre: "Florencia y Roma", 
      salida: "7 dic",
      regreso: "14 dic",
      precio: 1700, 
      cantidad: 1, 
      cantidadAdultos: 0, 
      cantidadNinos: 0
    },
    {
      id: 2, 
      img: "./img/paquetes/amalfitana.jpg",
      destino: "Italia",
      nombre: "Costa Amalfitana", 
      salida: "14 ene",
      regreso: "24 ene",
      precio: 1900, 
      cantidad: 1, 
      cantidadAdultos: 0, 
      cantidadNinos: 0
    },
    {
      id: 3, 
      img: "./img/paquetes/venecia.jpg",
      destino: "Italia",
      nombre: "Venecia", 
      salida: "14 dic",
      regreso: "21 dic",
      precio: 1700, 
      cantidad: 1, 
      cantidadAdultos: 0, 
      cantidadNinos: 0
    },
    {
      id: 4, 
      img: "./img/paquetes/paris.jpg",
      destino: "Francia",
      nombre: "Paris", 
      salida: "4 ene",
      regreso: "14 ene",
      precio: 2000, 
      cantidad: 1, 
      cantidadAdultos: 0, 
      cantidadNinos: 0
    },
    {
      id: 5, 
      img: "./img/paquetes/nisa.jpg",
      destino: "Francia",
      nombre: "Nisa", 
      salida: "10 ene",
      regreso: "17 ene",
      precio: 2000, 
      cantidad: 1, 
      cantidadAdultos: 0, 
      cantidadNinos: 0
    },
    {
      id: 6, 
      img: "./img/paquetes/marsella.jpg",
      destino: "Francia",
      nombre: "Marsella", 
      salida: "15 feb",
      regreso: "22 feb",
      precio: 2100, 
      cantidad: 1, 
      cantidadAdultos: 0, 
      cantidadNinos: 0
    },
    {
      id: 7, 
      img: "./img/paquetes/londres.jpg",
      destino: "Inglaterra",
      nombre: "Londres", 
      salida: "2 ene",
      regreso: "12 ene",
      precio: 1900, 
      cantidad: 1, 
      cantidadAdultos: 0, 
      cantidadNinos: 0
    },
    {
      id: 8, 
      img: "./img/paquetes/manchester.jpg",
      destino: "Inglaterra",
      nombre: "Manchester", 
      salida: "2 feb",
      regreso: "10 feb",
      precio: 2000, 
      cantidad: 1, 
      cantidadAdultos: 0, 
      cantidadNinos: 0
    },
    {
      id: 9, 
      img: "./img/paquetes/bristol.jpg",
      destino: "Inglaterra",
      nombre: "Bristol", 
      salida: "7 feb",
      regreso: "12 feb",
      precio: 2000, 
      cantidad: 1, 
      cantidadAdultos: 0, 
      cantidadNinos: 0
    },
    {
      id: 10, 
      img: "./img/paquetes/puntacana.jpg",
      destino: "Republica Dominicana",
      nombre: "Puntacana", 
      salida: "7 feb",
      regreso: "14 feb",
      precio: 1200, 
      cantidad: 1, 
      cantidadAdultos: 0, 
      cantidadNinos: 0
    },
    {
      id: 11, 
      img: "./img/paquetes/bayahibe.jpg",
      destino: "Republica Dominicana",
      nombre: "Bayahibe", 
      salida: "8 ene",
      regreso: "16 ene",
      precio: 1250, 
      cantidad: 1, 
      cantidadAdultos: 0, 
      cantidadNinos: 0
    },
    {
      id: 12, 
      img: "./img/paquetes/maya.jpg",
      destino: "Mexico",
      nombre: "Maravillas Mayas", 
      salida: "8 ene",
      regreso: "18 ene",
      precio: 1300, 
      cantidad: 1, 
      cantidadAdultos: 0, 
      cantidadNinos: 0
    },
    {
      id: 13, 
      img: "./img/paquetes/playadelcarmen.jpg",
      destino: "Mexico",
      nombre: "Playa del Carmen", 
      salida: "10 dic",
      regreso: "11 dic",
      precio: 1250, 
      cantidad: 1, 
      cantidadAdultos: 0, 
      cantidadNinos: 0
    },
    {
      id: 14, 
      img: "./img/paquetes/puertovallarta.jpg",
      destino: "Mexico",
      nombre: "Puerto Vallarta", 
      salida: "2 ene",
      regreso: "16 ene",
      precio: 1350, 
      cantidad: 1, 
      cantidadAdultos: 0, 
      cantidadNinos: 0
    },
    {
      id: 15, 
      img: "./img/paquetes/canaldepanama.jpg",
      destino: "Panama",
      nombre: "Canal de Panama", 
      salida: "16 ene",
      regreso: "21 ene",
      precio: 1100, 
      cantidad: 1, 
      cantidadAdultos: 0, 
      cantidadNinos: 0
    },
    {
      id: 16, 
      img: "./img/paquetes/sanblas.jpg",
      destino: "Panama",
      nombre: "San Blas", 
      salida: "3 feb",
      regreso: "11 feb",
      precio: 1350, 
      cantidad: 1, 
      cantidadAdultos: 0, 
      cantidadNinos: 0
    },
    {
      id: 17, 
      img: "./img/paquetes/orlando.jpg",
      destino: "Orlando",
      nombre: "Salida Diciembre", 
      salida: "13 dic",
      regreso: "23 dic",
      precio: 1550, 
      cantidad: 1, 
      cantidadAdultos: 0, 
      cantidadNinos: 0
    },
    {
      id: 18, 
      img: "./img/paquetes/orlando.jpg",
      destino: "Orlando",
      nombre: "Salida Enero", 
      salida: "3 ene",
      regreso: "13 ene",
      precio: 1650, 
      cantidad: 1, 
      cantidadAdultos: 0, 
      cantidadNinos: 0
    },
    {
      id: 19, 
      img: "./img/paquetes/orlando.jpg",
      destino: "Orlando",
      nombre: "Salida Febreo", 
      salida: "3 feb",
      regreso: "13 feb",
      precio: 1500, 
      cantidad: 1, 
      cantidadAdultos: 0, 
      cantidadNinos: 0
    },
    {
      id: 20, 
      img: "./img/paquetes/california.jpg",
      destino: "California",
      nombre: "Disney California", 
      salida: "10 feb",
      regreso: "25 feb",
      precio: 1800, 
      cantidad: 1, 
      cantidadAdultos: 0, 
      cantidadNinos: 0
    },
    {
      id: 21, 
      img: "./img/paquetes/lasvegas.jpg",
      destino: "California",
      nombre: "San Francisco y Las Vegas", 
      salida: "10 ene",
      regreso: "22 ene",
      precio: 1700, 
      cantidad: 1, 
      cantidadAdultos: 0, 
      cantidadNinos: 0
    },
    {
      id: 22, 
      img: "./img/paquetes/miami.jpg",
      destino: "Miami",
      nombre: "Paseo de Compras", 
      salida: "10 dic",
      regreso: "17 dic",
      precio: 1900, 
      cantidad: 1, 
      cantidadAdultos: 0, 
      cantidadNinos: 0
    },
    {
      id: 23, 
      img: "./img/paquetes/cayohueso.jpg",
      destino: "Miami",
      nombre: "Cayo Hueso", 
      salida: "21 ene",
      regreso: "1 feb",
      precio: 2200, 
      cantidad: 1, 
      cantidadAdultos: 0, 
      cantidadNinos: 0
    },
    {
      id: 24, 
      img: "./img/paquetes/buzios.jpg",
      destino: "Sur de Brasil",
      nombre: "Buzios", 
      salida: "4 feb",
      regreso: "10 feb",
      precio: 890, 
      cantidad: 1, 
      cantidadAdultos: 0, 
      cantidadNinos: 0
    },
    {
      id: 25, 
      img: "./img/paquetes/florianopolis.jpg",
      destino: "Sur de Brasil",
      nombre: "Florianopolis", 
      salida: "7 ene",
      regreso: "17 ene",
      precio: 850, 
      cantidad: 1, 
      cantidadAdultos: 0, 
      cantidadNinos: 0
    },
    {
      id: 26, 
      img: "./img/paquetes/rio.jpg",
      destino: "Centro de Brasil",
      nombre: "Río", 
      salida: "20 dic",
      regreso: "2 ene",
      precio: 1000, 
      cantidad: 1, 
      cantidadAdultos: 0, 
      cantidadNinos: 0
    },
    {
      id: 27, 
      img: "./img/paquetes/bahia.jpg",
      destino: "Centro de Brasil",
      nombre: "Bahia", 
      salida: "7 ene",
      regreso: "17 ene",
      precio: 950, 
      cantidad: 1, 
      cantidadAdultos: 0, 
      cantidadNinos: 0
    },
    {
      id: 28, 
      img: "./img/paquetes/natal.jpg",
      destino: "Norte de Brasil",
      nombre: "Natal", 
      salida: "17 ene",
      regreso: "31 ene",
      precio: 1200, 
      cantidad: 1, 
      cantidadAdultos: 0, 
      cantidadNinos: 0
    },
    {
      id: 29, 
      img: "./img/paquetes/portodegalinhas.jpg",
      destino: "Norte de Brasil",
      nombre: "Porto de Galinhas", 
      salida: "7 feb",
      regreso: "17 feb",
      precio: 1100, 
      cantidad: 1, 
      cantidadAdultos: 0, 
      cantidadNinos: 0
    },
    {
      id: 30, 
      img: "./img/paquetes/fortaleza.jpg",
      destino: "Norte de Brasil",
      nombre: "Fortaleza", 
      salida: "15 feb",
      regreso: "25 feb",
      precio: 1250, 
      cantidad: 1, 
      cantidadAdultos: 0, 
      cantidadNinos: 0
    }
  ]